const ts_class_to_tag_names = new Map(Object.entries({
    "HTMLAnchorElement" : ["a"],
    "HTMLAppletElement" : ["applet"],
    "HTMLAudioElement" : ["audio"],
    "HTMLAreaElement" : ["area"],
    "HTMLBaseElement" : ["base"],
    "HTMLBaseFontElement" : ["basefont"],
    "HTMLBodyElement" : ["body"],
    "HTMLBRElement" : ["br"],
    "HTMLButtonElement" : ["button"],
    "HTMLCanvasElement" : ["canvas"],
    "HTMLDirectoryElement" : ["dir"],
    "HTMLDivElement" : ["div"],
    "HTMLDListElement" : ["dl"],
    "HTMLEmbedElement" : ["embed"],
    "HTMLFieldSetElement" : ["fieldset"],
    "HTMLFontElement" : ["font"],
    "HTMLFormElement" : ["form"],
    "HTMLFrameElement" : ["frame"],
    "HTMLFrameSetElement" : ["frameset"],
    "HTMLHeadElement" : ["head"],
    "HTMLHeadingElement" : ["h1","h2","h3","h4","h5","h6"],
    "HTMLHtmlElement" : ["html"],
    "HTMLHRElement" : ["hr"],
    "HTMLIFrameElement" : ["iframe"],
    "HTMLImageElement" : ["img"],
    "HTMLInputElement" : ["input"],
    "HTMLKeygenElement" : ["keygen"],
    "HTMLLabelElement" : ["label"],
    "HTMLLIElement" : ["li"],
    "HTMLLinkElement" : ["link"],
    "HTMLMapElement" : ["map"],
    "HTMLMenuElement" : ["menu"],
    "HTMLMetaElement" : ["meta"],
    "HTMLModElement" : ["del", "ins"],
    "HTMLObjectElement" : ["object"],
    "HTMLOListElement" : ["ol"],
    "HTMLOptGroupElement" : ["optgroup"],
    "HTMLOptionElement" : ["option"],
    "HTMLOutputElement" : ["output"],
    "HTMLParagraphElement" : ["p"],
    "HTMLParamElement" : ["param"],
    "HTMLPreElement" : ["pre","plaintext"],
    "HTMLQuoteElement" : ["q","blockquote"],
    "HTMLScriptElement" : ["script"],
    "HTMLSelectElement" : ["select"],
    "HTMLSourceElement" : ["source"],
    "HTMLSpanElement" : ["span"],
    "HTMLStyleElement" : ["style"],
    "HTMLTableElement" : ["table"],
    "HTMLTableCaptionElement" : ["caption"],
    "HTMLTableDataCellElement" : ["td"],
    "HTMLTableHeaderCellElement" : ["th"],
    "HTMLTableColElement" : ["col", "colgroup"],
    "HTMLTableRowElement" : ["tr"],
    "HTMLTableSectionElement" : ["tfoot", "thead", "tbody"],
    "HTMLTextAreaElement" : ["textarea"],
    "HTMLTimeElement" : ["time"],
    "HTMLTitleElement" : ["title"],
    "HTMLTrackElement" : ["track"],
    "HTMLUListElement" : ["ul"],
    "HTMLUnknownElement" : ["bgsound", "isindex", "bq", "nextid", "multicol", "spacer", "noframes"],
    "HTMLVideoElement" : ["video"],
    }));

const tag_name_to_class = new Map();

for (const [ts_class_name,  tag_names] of ts_class_to_tag_names) {
    for (const tag_name of tag_names) {
        tag_name_to_class.set(tag_name, ts_class_name);
    }
}

export {ts_class_to_tag_names,tag_name_to_class};
