runtime: python310
version: 1
api_version: 1
threadsafe: false
service: default

handlers:
- url: /icon-home.png
  static_files: static/images/icon-home.png
  upload: static/images/icon-home.png

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /how.png
  static_files: static/images/how.png
  upload: static/images/how.png

- url: /amsterdam.png
  static_files: static/images/amsterdam.png
  upload: static/images/amsterdam.png

- url: /CLRS.jpeg
  static_files: static/images/CLRS.jpeg
  upload: static/images/CLRS.jpeg

- url: /Skiena.jpg
  static_files: static/images/Skiena.jpg
  upload: static/images/Skiena.jpg

- url: /Wirth.jpg
  static_files: static/images/Wirth.jpg
  upload: static/images/Wirth.jpg

- url: /sedgewick.png
  static_files: static/images/sedgewick.png
  upload: static/images/sedgewick.png

- url: /privacy.html
  static_files: static/html/privacy.html
  upload: static/html/privacy.html

- url: /user
  script: auto
  login: required

- url: /save
  script: auto
  login: required

- url: /delete
  script: auto
  login: required

- url: /share
  script: auto
  login: required

- url: /show
  script: auto

- url: /run
  script: auto

- url: /all.js
  static_files: static/js/all.js
  upload: static/js/all.js

- url: /.*
  script: auto


app_engine_apis: true

env_variables:
  GOOGLE_CLOUD_PROJECT: "pyalgoviz-361922"
